version: '3.6'

services:
  # application and web server
  app:
    image: my/app
    deploy:
      replicas: 1
    volumes:
      - ./app:/data/app
    env_file: postgres/env
    entrypoint: sh entry.sh

  nginx:
    image: my/nginx
    deploy:
      replicas: 1
    ports:
      - 80:80
    volumes:
      - ./app:/data/app

  # database and caching
  postgres:
    image: postgres:10.3-alpine
    deploy:
      replicas: 1
    volumes:
      - ./postgres/storage:/var/lib/postgresql
    env_file: postgres/env

  memcached:
    image: memcached:1.5-alpine
    deploy:
      replicas: 1
    entrypoint:
      - memcached
      - -m 64
